# Derived from vendor archive; see legacy provenance.

# bcd[3:0]
set_property PACKAGE_PIN Y1 [get_ports {bcd[3]}]
set_property PACKAGE_PIN W3 [get_ports {bcd[2]}]
set_property PACKAGE_PIN U2 [get_ports {bcd[1]}]
set_property PACKAGE_PIN T1 [get_ports {bcd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {bcd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {bcd[0]}]

# seg_data[7:0]
set_property PACKAGE_PIN P1 [get_ports {seg_data[7]}]
set_property PACKAGE_PIN P3 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN P7 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN N3 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN T5 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN R2 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN R4 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN R6 [get_ports {seg_data[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]